services:
  opensearch:
    image: opensearchproject/opensearch:3.3.0
    environment:
      discovery.type: single-node
      plugins.security.disabled: "true" # disable https and logins
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: "StrongPassword" # must have
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer

  # console at http://localhost:5601/app/dev_tools#/console
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:3.3.0
    ports:
      - 5601:5601
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"
